# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161022d27ab3812dce0e8b4c0e00a44c0cb1c3abb274e756e0b8badedfca0ce7d345721f478e8b515bd739d5db51bdb57a1914094bf15e0784ec7f22a63162cf

test:
  secret_key_base: 47c7578a5d1d02da759ee2069c10e7543067c59bd86c66b5717d9bf3079047164e0fafba241fe663dbfa9ae2e1f759b95b35468c23ac388204b5ff8508f896a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
